### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by ccamel** [okp4/ui#119]
## Propose a visual feature

![not-ready](https://img.shields.io/badge/status-notready-yellow.svg)
### **Purpose**

The `button` component is at the heart of the design system because it allows the user to express actions within the interface in which he evolves. This is why the design of this component is particularly important to offer the best possible User eXperience.
The `button` component must be sufficiently configurable to fully integrate into the style and philosophy of the ØKP4 design system.

### **Visual**

**Dark theme**

<img width="227" alt="image" src="https://user-images.githubusercontent.com/9574336/162460342-c4c7ad08-f07a-4cd1-8165-ae797248e057.png">

**Light theme**

<img width="222" alt="image" src="https://user-images.githubusercontent.com/9574336/162460472-91c381aa-28ab-484a-9b82-c5c68961ad1c.png">

### **Use cases**

The use cases associated with the `button` component are very numerous and varied, but in most cases allow to mark a **user action**.

### **Specification**
N/A

### **Notes**
N/A

**Comment by fredericvilcot** [comment]
@ccamel 
I will purpose the following specifications, let me know what you think.

**Props**
- `variant?: 'primary' | 'secondary'`: the variant to use.
- `color?: 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info'`: the color of the component, regarding the current theme and following semantic color naming.
- `size?: 'small' | 'medium' | 'large'`: the size of the rendered component.
- `disabled?: boolean`: if true, the component is disabled.
- `startIcon?: React.ReactNode`: an icon component placed before the children.
- `endIcon?: React.ReactNode`: an icon component placed after the children.
- `children?: React.ReactNode`: the content of the `button` component.

**State**

N/A

**Comment by fredericvilcot** [comment]
@ErikssonJoakim FYI

**Comment by fredericvilcot** [comment]
@ccamel maybe we could simply a bit by removing `startIcon` and `endIcon` and giving this responsibility to the caller which could provide (or not) an `icon` component directly into `children` element?

**Comment by ccamel** [comment]
@fredericvilcot Yes. I agree. Let's use the possibilities given by the property `children` to let the caller manage the icons.

**Comment by fredericvilcot** [comment]
@ccamel For now, I'll suggest to only implement a `label` to customize button's content and, in a very next future, we will implement icons as `children` elements.
