### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by ccamel** [okp4/ui#120]
## Propose a visual feature

![not-ready](https://img.shields.io/badge/status-notready-yellow.svg)
### **Purpose**

_TBD_

### **Visual**

**Dark theme**

<img width="327" alt="image" src="https://user-images.githubusercontent.com/9574336/162462879-31707e05-5cbf-4953-9617-4df32912c4c3.png">

**Light theme**

<img width="326" alt="image" src="https://user-images.githubusercontent.com/9574336/162462940-1731936a-da9d-4456-a7c4-239ee01c2a3a.png">

### **Use cases**

_TBD_

### **Specification**

_TBD_

### **Notes**

_TBD_

**Comment by nperon** [comment]
props:

body?: string,
topRightLabel?: string,
bottomLeftLabel?: string,
bottomRightLabel?: string,
size: 'small' | 'medium' | 'large',
background?: 'image1' | 'image2' | 'image3',
onClick?: ()=> void

**Comment by fredericvilcot** [comment]
After review with @nperon , specifications could be : 

- `content?: JSX.Element`,
- `footer?: JSX.Element`,
- `header?: JSX.Element`,
- `size: 'small' | 'medium' | 'large'`,
- `background?:` 'primary' | 'secondary' | 'header' | 'footer'`,
- `withBorder?: boolean`

@ccamel @ErikssonJoakim what do you think ?

**Comment by ccamel** [comment]
Good to me too 👍
