### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by ccamel** [okp4/ui#122]
## Propose a visual feature

![not-ready](https://img.shields.io/badge/status-notready-yellow.svg)
### **Purpose**

The `Select`component allows the user to choose from a list of options.

### **Visual**

**Dark theme**

<img width="462" alt="Capture d’écran 2022-06-21 à 16 42 07" src="https://user-images.githubusercontent.com/35332974/174827904-50b8bd94-dadd-49b8-9ff6-e212148b9cf1.png">

**Light theme**

<img width="459" alt="Capture d’écran 2022-06-21 à 16 42 15" src="https://user-images.githubusercontent.com/35332974/174827943-89ac181e-090f-4605-a180-91deb58680b4.png">

### **Use cases**

Whenever we want to offer the user the possibility to choose among several options.

#### Typology

`Select` is a molecule component.

#### Properties

`defaultValue?: string`: the value which is displayed to the user when the component is not controlled
`label?: string`: used as the select title
`options: Array<Option>`: a list of objects which contains a label and an associated value
`onChange`: the callback function passed by the parent to specify what is happening when an option is selected
`size?: small | medium | large` : The size of the select, defaultValue will be `medium`
`value`: the value selected by the user. If an empty string is passed `' '`, no option is selected
See API [reference](https://www.radix-ui.com/docs/primitives/components/select#api-reference) 

type Option = {
  label: string,
  value: string,
  group?: string,
}

#### State

- `value?: <Record<string, unknown>`: the selected value

### **Notes**

NA

**Comment by lolottetheclash** [comment]
@ccamel @fredericvilcot @ErikssonJoakim @JoeyDjr Here is the first version of the select component to implement. 
There are certainly additions/modifications to bring, do not hesitate!

**Comment by ccamel** [comment]
Great. Some remarks:
- is it envisaged that the component manages the auto-completion? I don't think so, but I ask.
- don't use `unknown` as type, but a generic `<T>`
- how the defaultValue works? I mean, could you define a default value which is not part of the options? The signature suggests it's the case, but I'd like confirmation.

**Comment by lolottetheclash** [comment]
@ccamel thank you for your feedback.
I think that the `auto-completion` should be implemented in order to propose the most complete component possible, but maybe after the v0. 
The `option`type was not yet defined, it was to be refined later indeed.
I think that the `defaultValue` should be part of the present options, it seems more logical to me but it is possible that I miss a subtlety...
Can you validate (or not) my feedback @fredericvilcot ?

**Comment by fredericvilcot** [comment]
@ccamel @lolottetheclash 

- the base `select` component will not handle `auto-completion` as Radix UI does not handle it. We must implement later a new dedicated `AutoComplete` component that will also handle tags.
- Yep, I wrote down a generic type to give the main idea but it's definitely not the final type. Will be more:
```typescript
export type Option = {
  label: string,
  value: string, // for now but should be extended later with JSX ...
  group: string,
  ....
}
```
- the `default` value must be part of base options, if not the value is not considered.

**Comment by ccamel** [comment]
Ok I see. Thanks for all the clarifications. Please update the above specification accordingly, so we can do a final review together before implementation. @fredericvilcot @lolottetheclash 

Last remarks:
- If the `default` value is part of the base options, then we only need the key (there's no need for the `Record<>`).
- We're agree that internationalization is not addressed by the component? Handled by the caller (who will provide the final translation).

**Comment by lolottetheclash** [comment]
@ccamel the `defaultValue` will be an `Option.value`, so a string in our case (indeed, no need for the Record<>).
I think that internationalization will be handled by the caller, the `Select` component will only receive the string translation.
@fredericvilcot int the Option type, I think that `group` must be optional what do you think?

**Comment by fredericvilcot** [comment]
@lolottetheclash yes, it must be optional as the user might not want to group the items in the select.
@ccamel, as @lolottetheclash said, internationalization will be handled by the caller by providing i18n keys as labels.
