### ISSUE TITLE
The "Don't Fear The Monad" Initiative

### ISSUE THREAD

**Issue by ccamel** [okp4/ui#277]
### **Purpose**

<img align="right" width="198" alt="image" src="https://user-images.githubusercontent.com/9574336/173538622-babee4f7-3522-417a-9e94-6be6b7a61c4f.png">

With @fredericvilcot  we defend the idea that the functional paradigm is likely to bring many good things for the realization of our applications. I will not go into the details of all the benefits, they are numerous, but we can mention: brevity, expressiveness, code concision, maintainability, safety, concurrency...

The current project uses an essentially imperative and object style, mainly because this is the natural paradigm. The initiative that is carried by this issue is to launch an initiative that aims to instil a functional style into the project in small steps, where it is relevant to do so. It should be noted that this initiative does not aim to refactor all the code in (pure) functional programming, and in doing so, go against the natural style of the language used which is Typescript, a not purely functional programming language, although it provides a lot of concepts that are in line with functional programming principles. The initiative aims to gain acceptance for the idea of a multi-paradigm coding style where, depending on what is to implement, a functional approach will be more appropriate. 

### Scope

The scope of the initiative is not strictly limited, but includes the following actions to be taken:

- immutable variables
- functions (instead of classes)
- purity / no side effects, as much as possible
- no throw of exceptions

![](https://www.memecreator.org/static/images/memes/5284527.jpg)

### How

The initiative provides for the use of any library that facilitates the expression of functional traits in code, and at first considers the library [gcanti/fp-ts](https://github.com/gcanti/fp-ts),  a library for typed functional programming in TypeScript. The first steps of the initiative will therefore be the declaration of this library and the application of some of the offered patterns like: [Option](https://gcanti.github.io/fp-ts/modules/Option.ts), [Either](https://gcanti.github.io/fp-ts/modules/Either.ts), [Task](https://gcanti.github.io/fp-ts/modules/Task.ts)...

### **Notes**

- [Functional programming](https://en.wikipedia.org/wiki/Functional_programming)
- [gcanti/fp-ts](https://github.com/gcanti/fp-ts)
- [A gentle introduction to monads](https://kristofsl.medium.com/a-gentle-introduction-to-monads-bc583d41d95)

**Comment by fredericvilcot** [comment]
@ccamel let's be functional! 🚀
