### ISSUE TITLE
🪐 Add 3D engine component

### ISSUE THREAD

**Issue by ccamel** [okp4/ui#369]
### **Purpose**

Following the implementation of the [Canvas](https://ui.okp4.space/?path=/docs/atoms-canvas--overview) component, it is now time to introduce a higher level component capable of handling our complex graphic rendering needs, especially for the purpose of displaying and exploring knowledge graphs in the Dataverse.

The component specified here is based on a 3D rendering engine, identified for its rendering capabilities: [babylonjs](https://www.babylonjs.com/). Although there are several alternative solutions, we feel that this one meets all our requirements:

- 3D engine on the browser with maximum compatibility
- full support for [WebGPU](https://doc.babylonjs.com/advanced_topics/webGPU/computeShader) (GLSL, shaders)
- build scene and components with ease
- TypeScript compatible
- ...

The main objective is to be able to visualize graphs of several thousand nodes. 

### **Visual**

N/A

### **Use cases**

The component specified here is an intermediate component, which offers in terms of capabilities only the functionality of the underlying 3D engine. So, the staging of the component should simply repeat the existing examples, with a wow effect if possible.

#### **Typology**

Component is an atom.

#### **Properties**

The properties of the component are essentially dictated by the underlying 3D engine. Very basically:

- `antialias?: boolean`: Enable antialiasing.
- `adaptToDeviceRatio?: boolean`: Defines whether to adapt to the device's viewport characteristics.
- `options?: EngineOptions`: Further options for the babylone engine.
- `touchActionNone?: boolean`: Defines if "touch-action: 'none'" is on the canvas.
- `disableScrolling?: boolean`: Disable scrolling on the canvas element so that it doesn't interfere with zoom in/out actions.
- `width?: number`: Width of the component (canvas).
- `height?: number`: Height of the component (canvas).
- `onEngineCreated?: EngineCreatedCallback<STATE>`: Called when engine is created. Can be used to configure the engine afterwards.
- `onRender?: RenderCallback<STATE>`: Called when rendering - see [Engine.runRenderLoop()](https://doc.babylonjs.com/typedoc/classes/BABYLON.Engine#runRenderLoop)

#### **State**

There's some local state to manage the babylon stuff, especially the [BABYLON.engine](https://doc.babylonjs.com/typedoc/classes/BABYLON.Engine) instance. 

### **Notes**

N/A

**Comment by warstrolo** [comment]
There is this one for rendering objects : https://threejs.org/

**Comment by ccamel** [comment]
Yep. @warstrolo. `babylonjs` and `threejs` compete at the same level (as WebGL engines). See: https://javascript.plainenglish.io/webgl-frameworks-three-js-vs-babylon-js-36975d915694. But the evaluations conducted so far lead us to believe that [babylonjs](https://www.babylonjs.com/) is more suitable for our needs.

**Comment by warstrolo** [comment]
Yup I've seen this article :)
