### ISSUE TITLE
🍞 Enhance Toast component

### ISSUE THREAD

**Issue by ErikssonJoakim** [okp4/ui#375]
### **Purpose**

As of now the content of the `Toast` component are `title` and `description` which are both strings. We want to be able to render any JSX Element in the toaster to give it more flexibility.

### **Visual**

![Capture d’écran 2022-07-21 à 13 45 46](https://user-images.githubusercontent.com/75730728/180206244-309da6ef-44b1-4a2b-b1e5-9dec52e9f1ed.png)

### **Use cases**

A use case with a complex JSX Element should be shown in the `content` story.

#### **Properties**

- description: `JSX.Element | string`

**Comment by fredericvilcot** [comment]
@ErikssonJoakim 
I forgot to tell you, but, `description` property should be an union of both `string` and `JSX.Element` types.
Doing that, it will not bring breaking changes and we could keep string elements in components that already use `Toast`
