### ISSUE TITLE
🏖️ add elements to button component

### ISSUE THREAD

**Issue by ErikssonJoakim** [okp4/ui#379]
### **Purpose**

Following the implementation of the Icon component it would be nice to give the user the option to add elements to the sides of the `button` component

### **Visual**

<img width="228" alt="Capture d’écran 2022-07-21 à 16 40 51" src="https://user-images.githubusercontent.com/75730728/180242092-fcc4335f-031a-4dd0-adeb-da94a39f0a51.png">
<img width="228" alt="Capture d’écran 2022-07-21 à 16 42 07" src="https://user-images.githubusercontent.com/75730728/180242377-9fdcc7f4-9485-4e01-9956-519f6d95be98.png">

### **Use cases**

This feature will allow users to create more complex buttons, adding images or other elements to the button

#### **Properties**

- leftElement: `JSX.Element`
- rightElement: `JSX.Element`

**Comment by fredericvilcot** [comment]
@ErikssonJoakim 
I would also like to be able to use the `button` as a simple icon without `label` and with a `title` attribute to enhance UX.
