### ISSUE TITLE
🤖 Automatically updating icon names

### ISSUE THREAD

**Issue by ErikssonJoakim** [okp4/ui#419]
### **Purpose**

As of now each time we add an icon we have to add an icon name manually in `Icon.tsx` as well as its story. 
I propose we create a new file which contains an array of all `icon names` as well as a type of the elements in the array and a script that checks `assets/icons` for new icons and adds their name to the array.

This way we can get rid of the boilerplate array in the story and we eliminate the risk of not adding the icon name to the list, presuming we use script systematically.

### **Use cases**

launching the script adds newly added icons to the `icon` component and its stories.

### **Acceptance Criteria**

- If array of icon names do not match the file names in assets/icons. 
- Then add missing name to the array.

Also, here are a few points that need to be addressed:

Constraint 1: the theme postfix and extension of the icon file names should not be included when adding to the icon names array.
Constraint 2: the file sprite.svg should not be included.
Constraint 3: The `Icon` component and its stories should only have 1 source of truth when it comes to icon names.

### **Notes**

Ideally this script should be part of a pre-push git hook that launches automatically whenever we use git push.

**Comment by ccamel** [comment]
@ErikssonJoakim I don't particularly like git hooks, and I generally consider them a bad practice, especially if they block commit or push. When it's the opposite we want: commit often, push often. Of course, if a developer wants to configure it in his environment, that's up to him. But it can't be imposed.

However, as part of this issue, we need to make sure that the CI checks that the files are is sync. You should add this in the UCs I guess.

**Comment by fredericvilcot** [comment]
The design system will be fully updated with a brand new design and all the icons will be deprecated and replaced by new ones.

Moreover, IMHO, we had too much issues with the use of `sprite` svgs (no possibility to modify colors, strokes, fonts...) so I'll suggest to get back to the use of `inline` svgs that are much more configurable in a generic way.

So, I close this issue.
