### ISSUE TITLE
📏 Refactor component stories

### ISSUE THREAD

**Issue by ErikssonJoakim** [okp4/ui#459]
📄 

Now that we have a dedicated wiki for [how to create a story](https://github.com/okp4/ui/wiki/Create-A-Story) we should refactor our existing component stories so that they follow these requirements.
**ATOMS**
- [ ] #623
- [x] #466
- [x] #624
- [x] #543 
- [ ] #625
- [x] #486 
- [x] #626
- [ ] #627
- [ ] #628
- [ ] #629
- [x] #630
- [ ] #631
- [ ] #632
- [x] #633

**MOLECULES**
- [ ] #634
- [ ] #635
- [ ] #636
- [ ] #637

**ORGANISMS**
- [ ] #638

**Comment by MdechampG** [comment]
@ErikssonJoakim : to split

**Comment by fredericvilcot** [comment]
Will be part of new incoming components
