### ISSUE TITLE
⏳ Package upgrades

### ISSUE THREAD

**Issue by lolottetheclash** [okp4/ui#576]
### **Purpose**
The purpose of this issue is to stay up to date on all the packages of our UI library.
Dependabot helps us on a daily basis, but we can also take care of upgrading some of our packages without waiting.
This allows us to go and "pick" packages to update when we have some bandwidth , and to stay as up to date as possible.

To do this, we can use the `yarn outdated` command which displays all the packages in our library, our version and the current version of the package. 

This is what it looks like:

![Capture d’écran 2022-10-13 à 16 19 28](https://user-images.githubusercontent.com/35332974/195622521-0ed0b8b6-0bb7-4b86-bee6-4140c92cc865.png)

I suggest you don't hesitate to work on it from time to time :)

**Comment by MdechampG** [comment]
Deprecated
